server:
  port: 8080
spring:
  cloud:
    function:
      definition: getKafkaMessage
    stream:
      bindings:
        getKafkaMessage-in-0:
          destination: ARCTYPE.public.t_user,ARCTYPE.public.document
          contentType: application/json
          consumer:
            concurrency: 2
      kafka:
        binder:
          brokers: localhost:29092
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bars
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        type: trace
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:master.yaml
    enabled: true
